name: notetakr
description: A powerful student note taking app

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  # Our Dependencies:
  flutter_localizations:
    sdk: flutter 
  flare_splash_screen: ^3.0.0
  flutter_local_notifications: ^0.8.4
  sqflite:
  path:
  http: 
  json_serializable: ^3.2.3
  speech_recognition: ^0.3.0
  charts_flutter: ^0.8.1
  data_tables: ^1.0.1
  cloud_firestore:
  flutter_map: 
  latlong:
  geolocator: '5.1.1'
  flutter_slidable: "^0.5.4"
  pull_to_refresh: ^1.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.4"

# If the launcher icon does not change run
# flutter pub pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "assets/images/pencil_launcher.png"
  android: "launcher_icon"
  ios: true  

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - lang/en.json
    - lang/fr.json
    - lang/es.json
    - lang/it.json
    - lang/ru.json
    - assets/
    - assets/images/
    
